# Generated by Django 2.2 on 2019-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Enter the content of the article', max_length=10000)),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
